[build]
  functions = "functions"

[[redirects]]
  from = "/search/*"
  to = "/.netlify/functions/app/search/:splat"
  status = 200

git commit -m "Initial commit"
git remote add origin <your_remote_repository_url>
git push -u origin master